### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dsmnoi** [tension/NeWorld-New-Theme-For-WHMCS#1]
用户中心 widget
被隐藏的公告 都显示出来了

**Comment by tension** [comment]
截图呢？

**Comment by dsmnoi** [comment]
你的支持whmcs 7
我在想是不是不支持whmcs 6 的原因
因为我用的是whmcs6 用了你的主题 被隐藏的公告 都显示出来了
等会给你截图

**Comment by tension** [comment]
这个主题支持最低 7.4.2！
