### ISSUE TITLE
domain order

### ISSUE THREAD

**Issue by insxa** [tension/NeWorld-New-Theme-For-WHMCS#2]
On checkout page there is bug when ordering domain, no promo code input, and domain name is strike.
![fireshot screen capture 003 - korpa - duohost - moj_duo_rs_cart_php_a view](https://user-images.githubusercontent.com/19369515/36731358-c975c0b2-1bca-11e8-8cab-00d4720ffc36.png)

**Comment by tension** [comment]
Thank you for asking questions! Fixed!
