### ISSUE TITLE
插件模块出错？

### ISSUE THREAD

**Issue by shenzt68** [tension/NeWorld-New-Theme-For-WHMCS#3]
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Whoops\Exception\ErrorException: require(): Failed opening required '/www/wwwroot/xx.xx.com/modules/addons/NeWorld/library/class/NeWorld.Common.Class.php' (include_path='.:/www/server/php/70/lib/php') in /www/wwwroot/xx.xx.com/modules/addons/NeWorldUI/NeWorldUI.php:8
Stack trace:
#0 /www/wwwroot/xx.xx.com/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require(): Fail...', '/www/wwwroot/t1...', 8)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by goolissfun** [comment]
没安neworld-manager

**Comment by tension** [comment]
请仔细查看说明ok？

**Comment by shenzt68** [comment]
没安neworld-manager?这个在哪里呢？
