### ISSUE TITLE
bug 解决一下  (附上截图)

### ISSUE THREAD

**Issue by dsmnoi** [tension/NeWorld-New-Theme-For-WHMCS#5]
上次跟你提过
用户中心 widget 被隐藏的公告 都显示出来了

你说要最低支持whmcs 7.4.2
今天由6.3.1 升级 7.4.2

将主题重新安装
bug依然存在 请修复一下

![testr](https://user-images.githubusercontent.com/11258805/37885900-5eea454e-30ea-11e8-9cec-f3b27a5ef94e.PNG)
![test2](https://user-images.githubusercontent.com/11258805/37885901-5f16328a-30ea-11e8-9c8d-5f5ba8c25195.PNG)

**Comment by tension** [comment]
修复
